### ISSUE TITLE
Mapa Mental-Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/mapa-mental-Edwin14459#2]
[Mapa Mental-Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-Edwin14459/files/7281182/Mapa.Mental-Edwin.Lopez.Santiago.pdf)

**Comment by 7177981** [comment]
realizo un buen trabajo incluyo imágenes de acuerdo al tema, en cuanto colores es muy llamativo, contiene información precisa
calificación = 97%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
